### ISSUE TITLE
后台

### ISSUE THREAD

**Issue by cs0618-ui** [monyuan/notify-me#1]
你好 请问后台在哪 我该怎样把我的密钥添加进插件

**Comment by monyuan** [comment]
安装了插件后后，你的halo后台左边菜单栏不是有“通知我”这个选项吗，你进去之后配置就行了

**Comment by cs0618-ui** [comment]
你好 我进去之后没有配置选项







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月3日(星期三) 下午5:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [monyuan/notify-me] 后台 (Issue #1)





 
安装了插件后后，你的halo后台左边菜单栏不是有“通知我”这个选项吗，你进去之后配置就行了

**Comment by monyuan** [comment]
能否提供一下你的后台截图和halo版本

**Comment by cs0618-ui** [comment]
> 能否提供一下你的后台截图和halo版本

![image](https://github.com/monyuan/notify-me/assets/153248531/7881bcf5-e63a-40e4-8dee-14b267c38c30)

**Comment by cs0618-ui** [comment]
请问halo版本可以在哪看

**Comment by monyuan** [comment]
能够提供下微信，我帮你看看

**Comment by cs0618-ui** [comment]
> 能够提供下微信，我帮你看看

mztkn0504

**Comment by monyuan** [comment]
已添加，我把你这个微信号的评论删掉

**Comment by cs0618-ui** [comment]
好的 谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月3日(星期三) 下午5:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [monyuan/notify-me] 后台 (Issue #1)





 
已添加，我把你这个微信号的评论删掉

**Comment by monyuan** [comment]
通过一下

**Comment by cs0618-ui** [comment]
不好意思 刚刚发错了 mztkn504多了一个0




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月3日(星期三) 晚上6:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [monyuan/notify-me] 后台 (Issue #1)





 
通过一下

**Comment by monyuan** [comment]
已解决，在管理后台左侧菜单栏一直往后拉，即可找到
