### ISSUE TITLE
新评论推送失败

### ISSUE THREAD

**Issue by 516966395** [monyuan/notify-me#2]
anpush 报文  大佬麻烦看一下

{
 "errcode": 47003,
 "errmsg": "argument invalid! data.thing4.value invalid rid: 65962673-2de048c2-766e4fde"
}

**Comment by 516966395** [comment]
新文章推送正常      评论审核未推送

**Comment by monyuan** [comment]
使用的是微信推送模板吧，我看看你文章的标题

**Comment by 516966395** [comment]
是的微信的       标题是    测试微信推送

**Comment by monyuan** [comment]
不要包含“微信”这个关键词，还是不行就使用最新发布的版本

**Comment by 516966395** [comment]
okok
