### ISSUE TITLE
保存失败,请检查API密钥和通道ID是否正确

### ISSUE THREAD

**Issue by Dominic-KK** [monyuan/notify-me#4]
获取的应该都没问题吧，通道测试也正常发送
![image](https://github.com/monyuan/notify-me/assets/76522991/bbf455ed-3582-41f1-b6bd-43e0ff8d3bd1)
![image](https://github.com/monyuan/notify-me/assets/76522991/29d8bdbd-1826-4ad1-a0a2-fb5cd53f64ab)
![image](https://github.com/monyuan/notify-me/assets/76522991/df652b07-f322-4cc2-8499-cbef2f8faea5)

**Comment by monyuan** [comment]
F12帮忙看下halo后台插件接口返回的什么

**Comment by monyuan** [comment]
测试了一下，是你点太快了，刷新下网页就好了。如果没问题就close了

**Comment by Dominic-KK** [comment]
刷新没用，接口没有返回数据，请求错误了，没有状态码
![image](https://github.com/monyuan/notify-me/assets/76522991/a8754542-25e0-4973-b76f-edad908bdfbd)

**Comment by monyuan** [comment]
不介意的话把图截大一些，这看不出来什么，看看控制台报的什么错

**Comment by Dominic-KK** [comment]
我这边的问题，重启了halo正常了，谢谢！
