### ISSUE TITLE
halo2.12.1版本的装好插件启用后，左侧没有通知我的菜单

### ISSUE THREAD

**Issue by huangge1199** [monyuan/notify-me#6]
![image](https://github.com/monyuan/notify-me/assets/9335756/33360ca9-654a-42e6-b254-1eac98e5917c)

**Comment by huangge1199** [comment]
我重启容器后出现了。。。。。。。。。。。

**Comment by ruibaby** [comment]
> 我重启容器后出现了。。。。。。。。。。。

建议升级到 2.12.2，你这个版本包含一个 bug 可能会造成这个表现。
